require:
  - rubocop-performance

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Naming/FileName:
  Exclude:
    - 'lib/sidekiq-crond.rb'

Layout/LineLength:
  Max: 120
